
stages:
  - prebuild
  - containers
  - builds

.container_job_template: &container_job_definition
  image: docker:stable
  stage: containers
  needs: []
  services:
    - name: registry.gitlab.com/libvirt/libvirt-ci/docker-dind:master
      alias: docker
  before_script:
    - export TAG="$CI_REGISTRY_IMAGE/ci-$NAME:latest"
    - export COMMON_TAG="$CI_REGISTRY/libvirt/libvirt-dbus/ci-$NAME:latest"
    - docker info
    - docker login registry.gitlab.com -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker pull "$TAG" || docker pull "$COMMON_TAG" || true
    - docker build --cache-from "$TAG" --cache-from "$COMMON_TAG" --tag "$TAG" -f "ci/containers/ci-$NAME.Dockerfile" ci
    - docker push "$TAG"
  after_script:
    - docker logout

.script_variables: &script_variables |
  export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
  export SCRATCH_DIR="/tmp/scratch"
  export VROOT="$SCRATCH_DIR/vroot"
  export LIBDIR="$VROOT/lib"
  export CCACHE_DIR="$PWD/ccache"
  export CCACHE_MAXSIZE="500M"
  export PATH="$CCACHE_WRAPPERSDIR:$VROOT/bin:$PATH"
  export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
  export LD_LIBRARY_PATH="$LIBDIR"
  export XDG_DATA_DIRS="$VROOT/share:/usr/share"
  export GI_TYPELIB_PATH="$LIBDIR/girepository-1.0"

.git_native_build_job_template: &git_native_build_job_definition
  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
  stage: builds
  cache:
    paths:
      - ccache/
    key: "$CI_JOB_NAME"
  before_script:
    - *script_variables
  script:
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt-glib.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - cd ../libvirt-glib
    - meson build "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - meson build --fatal-meson-warnings -Dwerror=true --prefix="$VROOT"
    - $NINJA -C build
    - $NINJA -C build install;
    - if test "$TESTS" != "skip";
      then
        $NINJA -C build test;
        $NINJA -C build dist;
      fi
    - if test -x /usr/bin/rpmbuild && test "$RPM" != "skip";
      then
        rpmbuild --nodeps -ta build/meson-dist/libvirt-dbus*.tar.xz;
      fi

.dist_native_build_job_template: &dist_native_build_job_definition
  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
  stage: builds
  cache:
    paths:
      - ccache/
    key: "$CI_JOB_NAME"
  before_script:
    - *script_variables
  script:
    - meson build --fatal-meson-warnings -Dwerror=true --prefix="$VROOT"
    - $NINJA -C build
    - $NINJA -C build install;
    - if test "$TESTS" != "skip";
      then
        $NINJA -C build test;
        $NINJA -C build dist;
      fi
    - if test -x /usr/bin/rpmbuild && test "$RPM" != "skip";
      then
        rpmbuild --nodeps -ta build/meson-dist/libvirt-dbus*.tar.xz;
      fi


# Check that all commits are signed-off for the DCO.
# Skip on "libvirt" namespace, since we only need to run
# this test on developer's personal forks from which
# merge requests are submitted
check-dco:
  stage: prebuild
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  needs: []
  script:
    - /check-dco
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'libvirt'

x64-centos-7-container:
  <<: *container_job_definition
  variables:
    NAME: centos-7

x64-centos-8-container:
  <<: *container_job_definition
  variables:
    NAME: centos-8

x64-centos-stream-container:
  <<: *container_job_definition
  variables:
    NAME: centos-stream

x64-debian-10-container:
  <<: *container_job_definition
  variables:
    NAME: debian-10

x64-debian-sid-container:
  <<: *container_job_definition
  variables:
    NAME: debian-sid

x64-fedora-32-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-32

x64-fedora-33-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-33

x64-fedora-rawhide-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-rawhide

x64-opensuse-151-container:
  <<: *container_job_definition
  variables:
    NAME: opensuse-151

x64-ubuntu-1804-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-1804

x64-ubuntu-2004-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-2004



x64-centos-7-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-centos-7-container
  variables:
    NAME: centos-7
    TESTS: skip
    RPM: skip

x64-centos-8-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-centos-8-container
  variables:
    NAME: centos-8
    RPM: skip

x64-centos-stream-git-build:
  <<: *git_native_build_job_definition
  needs:
    - x64-centos-stream-container
  variables:
    NAME: centos-stream
    RPM: skip

x64-debian-10-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-debian-10-container
  variables:
    NAME: debian-10

x64-debian-sid-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-debian-sid-container
  variables:
    NAME: debian-sid

x64-fedora-32-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-fedora-32-container
  variables:
    NAME: fedora-32
    RPM: skip

x64-fedora-33-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-fedora-33-container
  variables:
    NAME: fedora-33

x64-fedora-rawhide-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-fedora-rawhide-container
  variables:
    NAME: fedora-rawhide

x64-opensuse-151-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-opensuse-151-container
  variables:
    NAME: opensuse-151
    RPM: skip

x64-ubuntu-1804-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-ubuntu-1804-container
  variables:
    NAME: ubuntu-1804

x64-ubuntu-2004-dist-build:
  <<: *dist_native_build_job_definition
  needs:
    - x64-ubuntu-2004-container
  variables:
    NAME: ubuntu-2004


# Coverity job that is run only by schedules
coverity:
  image: $CI_REGISTRY_IMAGE/ci-centos-8:latest
  needs:
    - x64-centos-8-container
  stage: builds
  script:
    - curl https://scan.coverity.com/download/linux64 --form project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN -o /tmp/cov-analysis-linux64.tgz
    - tar xfz /tmp/cov-analysis-linux64.tgz
    - meson build
    - cov-analysis-linux64-*/bin/cov-build --dir cov-int ninja -C build
    - tar cfz cov-int.tar.gz cov-int
    - curl https://scan.coverity.com/builds?project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN --form email=$GITLAB_USER_EMAIL --form file=@cov-int.tar.gz --form version="$(git describe --tags)" --form description="$(git describe --tags) / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID"
  only:
    refs:
      - schedules
    variables:
      - $COVERITY_SCAN_PROJECT_NAME && $COVERITY_SCAN_TOKEN
